
// Objective-C API for talking to the following Go packages
//
//	github.com/mindsgn-studio/pocket-money-app/core
//
// File is generated by gomobile bind. Do not edit.
#ifndef __PocketCore_FRAMEWORK_H__
#define __PocketCore_FRAMEWORK_H__

#include "Core.objc.h"
#include "Universe.objc.h"

#endif
